import { Router, type IRouter } from "express";
import { db, festivalDonationsTable, festivalExpensesTable, festivalsTable } from "@workspace/db";
import { and, desc, eq, gte, lte, sql } from "drizzle-orm";
import { canAccessFestival, requireRole } from "../middlewares/requireRole";

const router: IRouter = Router();
const adminOnly = requireRole("Super Admin", "Admin");
const categories = new Set(["Decoration", "Pooja", "Prasad / Food", "Sound System", "Electricity", "Pandal / Setup", "Transportation", "Printing", "Cleaning", "Other"]);
const methods = new Set(["cash", "upi", "cheque", "bank_transfer", "other"]);
const parseId = (value: unknown) => { const result = Number(value); return Number.isInteger(result) && result > 0 ? result : null; };
const currentAdmin = (req: any) => req.admin;
function logExpenseError(operation: string, festivalId: number | null, error: unknown) { console.error(`[festival-expenses] ${operation} failed`, { festivalId, error: error instanceof Error ? error.message : error }); }
async function canUseFestival(req: any, res: any, festivalId: number) { const [festival] = await db.select({ id: festivalsTable.id }).from(festivalsTable).where(eq(festivalsTable.id, festivalId)).limit(1); if (!festival) { res.status(404).json({ error: "Festival not found" }); return false; } if (!(await canAccessFestival(currentAdmin(req).role, currentAdmin(req).id, festivalId))) { res.status(403).json({ error: "Forbidden" }); return false; } return true; }
const validDate = (value: unknown) => typeof value === "string" && /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(Date.parse(`${value}T00:00:00Z`));
function input(body: any, partial = false) { const result: Record<string, unknown> = {}; if (!partial || body.expenseName !== undefined) result.expenseName = String(body.expenseName || "").trim(); if (!partial || body.category !== undefined) result.category = String(body.category || "").trim(); if (!partial || body.amount !== undefined) result.amount = String(body.amount || ""); if (!partial || body.paymentMethod !== undefined) result.paymentMethod = String(body.paymentMethod || ""); if (!partial || body.expenseDate !== undefined) result.expenseDate = String(body.expenseDate || ""); if (result.expenseName !== undefined && !result.expenseName || result.category !== undefined && !categories.has(String(result.category)) || result.amount !== undefined && (!Number.isFinite(Number(result.amount)) || Number(result.amount) <= 0) || result.paymentMethod !== undefined && !methods.has(String(result.paymentMethod)) || result.expenseDate !== undefined && !validDate(result.expenseDate)) return null; if (result.amount !== undefined) result.amount = Number(result.amount).toFixed(2); return result; }
async function summary(festivalId: number) { const [expense] = await db.select({ total: sql<string>`COALESCE(SUM(${festivalExpensesTable.amount}::numeric), 0)` }).from(festivalExpensesTable).where(eq(festivalExpensesTable.festivalId, festivalId)); const [donation] = await db.select({ total: sql<string>`COALESCE(SUM(${festivalDonationsTable.amount}::numeric) FILTER (WHERE ${festivalDonationsTable.paymentMethod} <> 'pending'), 0)` }).from(festivalDonationsTable).where(eq(festivalDonationsTable.festivalId, festivalId)); const totalExpenses = Number(expense?.total || 0); const totalDonations = Number(donation?.total || 0); const [methodsRows] = await db.select({ cash: sql<string>`COALESCE(SUM(${festivalExpensesTable.amount}::numeric) FILTER (WHERE ${festivalExpensesTable.paymentMethod} = 'cash'), 0)`, upi: sql<string>`COALESCE(SUM(${festivalExpensesTable.amount}::numeric) FILTER (WHERE ${festivalExpensesTable.paymentMethod} = 'upi'), 0)`, cheque: sql<string>`COALESCE(SUM(${festivalExpensesTable.amount}::numeric) FILTER (WHERE ${festivalExpensesTable.paymentMethod} = 'cheque'), 0)`, bankTransfer: sql<string>`COALESCE(SUM(${festivalExpensesTable.amount}::numeric) FILTER (WHERE ${festivalExpensesTable.paymentMethod} = 'bank_transfer'), 0)`, other: sql<string>`COALESCE(SUM(${festivalExpensesTable.amount}::numeric) FILTER (WHERE ${festivalExpensesTable.paymentMethod} = 'other'), 0)` }).from(festivalExpensesTable).where(eq(festivalExpensesTable.festivalId, festivalId)); return { totalExpenses, totalDonations, remainingMoney: totalDonations - totalExpenses, expenseCount: await db.select({ count: sql<number>`COUNT(*)::int` }).from(festivalExpensesTable).where(eq(festivalExpensesTable.festivalId, festivalId)).then(([row]) => row?.count || 0), cash: Number(methodsRows?.cash || 0), upi: Number(methodsRows?.upi || 0), cheque: Number(methodsRows?.cheque || 0), bankTransfer: Number(methodsRows?.bankTransfer || 0), other: Number(methodsRows?.other || 0) }; }
router.get("/admin/festivals/:festivalId/expenses", adminOnly, async (req, res) => { const festivalId = parseId(req.params.festivalId); if (!festivalId || !(await canUseFestival(req, res, festivalId))) return; try { const clauses: any[] = [eq(festivalExpensesTable.festivalId, festivalId)]; if (req.query.category) clauses.push(eq(festivalExpensesTable.category, String(req.query.category))); if (req.query.paymentMethod) clauses.push(eq(festivalExpensesTable.paymentMethod, String(req.query.paymentMethod))); if (req.query.dateFrom && validDate(req.query.dateFrom)) clauses.push(gte(festivalExpensesTable.expenseDate, String(req.query.dateFrom))); if (req.query.dateTo && validDate(req.query.dateTo)) clauses.push(lte(festivalExpensesTable.expenseDate, String(req.query.dateTo))); let expenses = await db.select().from(festivalExpensesTable).where(and(...clauses)).orderBy(desc(festivalExpensesTable.expenseDate), desc(festivalExpensesTable.createdAt)); const search = String(req.query.search || "").trim().toLowerCase(); if (search) expenses = expenses.filter(item => item.expenseName.toLowerCase().includes(search)); res.json({ expenses, summary: await summary(festivalId) }); } catch (error) { logExpenseError("list", festivalId, error); res.status(500).json({ error: "Unable to load festival expenses" }); }
});
router.get("/admin/festivals/:festivalId/expenses/summary", adminOnly, async (req, res) => { const festivalId = parseId(req.params.festivalId); if (!festivalId || !(await canUseFestival(req, res, festivalId))) return; res.json(await summary(festivalId)); });
router.post("/admin/festivals/:festivalId/expenses", adminOnly, async (req, res) => { const festivalId = parseId(req.params.festivalId); const values = input(req.body); if (!festivalId || !values) { res.status(400).json({ error: "Expense name, category, positive amount, payment method, and valid date are required" }); return; } if (!(await canUseFestival(req, res, festivalId))) return; const admin = currentAdmin(req); const [created] = await db.insert(festivalExpensesTable).values({ ...values, festivalId, createdByAdminId: admin.id, createdByAdminName: admin.fullName } as any).returning(); res.status(201).json(created); });
router.patch("/admin/festival-expenses/:expenseId", adminOnly, async (req, res) => { const expenseId = parseId(req.params.expenseId); const values = input(req.body, true); if (!expenseId || !values) { res.status(400).json({ error: "Invalid expense details" }); return; } const [existing] = await db.select().from(festivalExpensesTable).where(eq(festivalExpensesTable.id, expenseId)); if (!existing) { res.status(404).json({ error: "Expense not found" }); return; } if (!(await canUseFestival(req, res, existing.festivalId))) return; const [updated] = await db.update(festivalExpensesTable).set({ ...values, updatedByAdminId: currentAdmin(req).id } as any).where(eq(festivalExpensesTable.id, expenseId)).returning(); res.json(updated); });
router.delete("/admin/festival-expenses/:expenseId", adminOnly, async (req, res) => { const expenseId = parseId(req.params.expenseId); if (!expenseId) { res.status(400).json({ error: "Invalid expense ID" }); return; } const [existing] = await db.select().from(festivalExpensesTable).where(eq(festivalExpensesTable.id, expenseId)); if (!existing) { res.status(404).json({ error: "Expense not found" }); return; } if (!(await canUseFestival(req, res, existing.festivalId))) return; await db.delete(festivalExpensesTable).where(eq(festivalExpensesTable.id, expenseId)); res.status(204).end(); });
export default router;
