import { Router, type IRouter } from "express";
import multer from "multer";
import { createHmac, randomBytes } from "node:crypto";
import { db, buildingsTable, competitionEntriesTable, competitionEntryImagesTable, competitionSecurityAttemptsTable, competitionVotesTable, competitionsTable, residentsTable, wingsTable } from "@workspace/db";
import { and, desc, eq, gte, ne, sql } from "drizzle-orm";
import { z } from "zod/v4";
import { requireRole } from "../middlewares/requireRole";
import { cloudinary, isCloudinaryConfigured } from "../lib/cloudinary";

const router: IRouter = Router(), secret = process.env.VOTER_HASH_SECRET, turnstileSecret = process.env.TURNSTILE_SECRET_KEY;
const upload = multer({ storage: multer.memoryStorage(), limits: { files: 3, fileSize: 5 * 1024 * 1024 }, fileFilter: (_r, f, cb) => cb(null, ["image/jpeg", "image/png", "image/webp"].includes(f.mimetype)) });
const residentSchema = z.object({ fullName: z.string().trim().min(2).max(120), mobile: z.string().trim().min(7).max(25), buildingId: z.coerce.number().int().positive(), wingId: z.coerce.number().int().positive().nullable().optional(), flatNo: z.string().trim().min(1).max(30) });
const settingsSchema = z.object({ name: z.string().trim().min(3).max(160), category: z.string().trim().min(2).max(80).default("Ganpati Decoration"), description: z.string().trim().min(10).max(5000), status: z.enum(["draft", "registration_open", "voting_open", "voting_closed", "completed"]), date: z.string().datetime().optional(), registrationStart: z.string().datetime().nullable().optional(), registrationEnd: z.string().datetime().nullable().optional(), votingStart: z.string().datetime().nullable().optional(), votingEnd: z.string().datetime().nullable().optional(), maxImages: z.number().int().min(1).max(3).default(3), resultsPublished: z.boolean().optional() });
const id = (v: unknown) => { const r = z.coerce.number().int().positive().safeParse(v); return r.success ? r.data : null; };
const asDate = (v?: string | null) => v ? new Date(v) : null;
const open = (c: any, type: "registration" | "voting") => { const n = new Date(), status = `${type}_open`, start = c[`${type}Start`], end = c[`${type}End`]; return c.status === status && (!start || start <= n) && (!end || end >= n); };
function reqHashes(req: any) { const key = secret!; const h = (v: string) => createHmac("sha256", key).update(v).digest("hex"); const ip = String(req.headers["x-forwarded-for"] || req.ip || "").split(",")[0].trim(); return { ip, ipHash: h(`ip:${ip}`), userAgentHash: h(`ua:${req.get("user-agent") || ""}`) }; }
async function resident(data: z.infer<typeof residentSchema>) { const where = [eq(residentsTable.fullName, data.fullName), eq(residentsTable.mobile, data.mobile), eq(residentsTable.buildingId, data.buildingId), eq(residentsTable.flatNo, data.flatNo), eq(residentsTable.status, "active"), data.wingId == null ? sql`${residentsTable.wingId} IS NULL` : eq(residentsTable.wingId, data.wingId)]; return (await db.select({ id: residentsTable.id, fullName: residentsTable.fullName, buildingName: buildingsTable.buildingName, wingName: wingsTable.wingName }).from(residentsTable).innerJoin(buildingsTable, eq(residentsTable.buildingId, buildingsTable.id)).leftJoin(wingsTable, eq(residentsTable.wingId, wingsTable.id)).where(and(...where)).limit(1))[0]; }
function cloudUpload(buffer: Buffer) { return new Promise<{url:string;publicId:string}>((resolve, reject) => { const s = cloudinary.uploader.upload_stream({ folder: "meditiya-sathi/competitions", format: "webp", transformation: [{width:1600,height:1200,crop:"limit"},{quality:"auto:good"}] }, (e,r) => e || !r ? reject(e || Error("Upload failed")) : resolve({url:r.secure_url,publicId:r.public_id})); s.end(buffer); }); }
async function captcha(token: string, ip: string) { if (!turnstileSecret || !token) return false; try { const body = new URLSearchParams({secret:turnstileSecret,response:token,remoteip:ip}); const r = await fetch("https://challenges.cloudflare.com/turnstile/v0/siteverify", {method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body}); return r.ok && !!((await r.json()) as { success?: boolean }).success; } catch { return false; } }
async function attempt(req:any, competitionId:number, entryId:number | null, outcome:string) { if (!secret) return; const {ipHash,userAgentHash}=reqHashes(req); await db.insert(competitionSecurityAttemptsTable).values({competitionId,entryId,attemptType:"vote",outcome,ipHash,userAgentHash}).catch(()=>undefined); }

router.get("/competitions", async (_q,res) => { try { res.json(await db.select().from(competitionsTable).where(ne(competitionsTable.status, "draft")).orderBy(desc(competitionsTable.date))); } catch (error) { console.error("GET /api/competitions failed", error); res.status(500).json({ error: "Unable to load competitions." }); } });
router.get("/competitions/:id", async (req,res) => { try { const competitionId=id(req.params.id); const c=competitionId && (await db.select().from(competitionsTable).where(and(eq(competitionsTable.id,competitionId),ne(competitionsTable.status,"draft"))).limit(1))[0]; if(!c){res.status(404).json({error:"Competition not found"});return;} res.json({...c,registrationOpen:open(c,"registration"),votingOpen:open(c,"voting")}); } catch (error) { console.error("GET /api/competitions/:id failed", error); res.status(500).json({ error: "Unable to load competition." }); } });
router.get("/competitions/:id/entries", async(req,res)=>{const competitionId=id(req.params.id);if(!competitionId){res.status(400).json({error:"Invalid competition id"});return;} const rows=await db.select({id:competitionEntriesTable.id,title:competitionEntriesTable.title,description:competitionEntriesTable.description,residentName:residentsTable.fullName,buildingName:buildingsTable.buildingName,wingName:wingsTable.wingName,imageUrl:competitionEntryImagesTable.imageUrl,displayOrder:competitionEntryImagesTable.displayOrder,votes:sql<number>`COUNT(${competitionVotesTable.id})::int`}).from(competitionEntriesTable).innerJoin(residentsTable,eq(competitionEntriesTable.residentId,residentsTable.id)).innerJoin(buildingsTable,eq(residentsTable.buildingId,buildingsTable.id)).leftJoin(wingsTable,eq(residentsTable.wingId,wingsTable.id)).leftJoin(competitionEntryImagesTable,eq(competitionEntryImagesTable.entryId,competitionEntriesTable.id)).leftJoin(competitionVotesTable,eq(competitionVotesTable.entryId,competitionEntriesTable.id)).where(and(eq(competitionEntriesTable.competitionId,competitionId),eq(competitionEntriesTable.status,"approved"))).groupBy(competitionEntriesTable.id,residentsTable.fullName,buildingsTable.buildingName,wingsTable.wingName,competitionEntryImagesTable.id).orderBy(desc(sql`COUNT(${competitionVotesTable.id})`));const map=new Map<number,any>();rows.forEach(r=>{const e=map.get(r.id)||{...r,images:[]};delete e.imageUrl;delete e.displayOrder;if(r.imageUrl)e.images.push({imageUrl:r.imageUrl,displayOrder:r.displayOrder});map.set(r.id,e)});res.json([...map.values()]);});
router.post("/competitions/:id/verify-resident",async(req,res)=>{const competitionId=id(req.params.id), data=residentSchema.safeParse(req.body);const c=competitionId&&(await db.select().from(competitionsTable).where(eq(competitionsTable.id,competitionId)).limit(1))[0];if(!data.success||!c||!open(c,"registration")){res.status(403).json({error:"Resident verification is unavailable."});return;}const r=await resident(data.data);if(!r){res.status(403).json({error:"We could not verify these resident details."});return;}res.json({verified:true,resident:{fullName:r.fullName,buildingName:r.buildingName,wingName:r.wingName}})});
router.post("/competitions/:id/register",(req,res)=>upload.array("images",3)(req,res,async(error)=>{const competitionId=id(req.params.id), data=residentSchema.safeParse({...req.body,wingId:req.body.wingId||null}),title=String(req.body.title||"").trim(),description=String(req.body.description||"").trim(),files=(req.files||[]) as Express.Multer.File[];const c=competitionId&&(await db.select().from(competitionsTable).where(eq(competitionsTable.id,competitionId)).limit(1))[0];if(error||!data.success||!c||!open(c,"registration")||title.length<2||description.length<10||!files.length){res.status(400).json({error:"Provide verified resident details, entry details, and up to 3 valid images."});return;}if(!isCloudinaryConfigured){res.status(503).json({error:"Image uploads are not configured."});return;}const r=await resident(data.data);if(!r){res.status(403).json({error:"We could not verify these resident details."});return;}try{const imgs=await Promise.all(files.slice(0,c.maxImages).map(f=>cloudUpload(f.buffer)));const entry=await db.transaction(async tx=>{const [e]=await tx.insert(competitionEntriesTable).values({competitionId,residentId:r.id,title,description}).returning();await tx.insert(competitionEntryImagesTable).values(imgs.map((image,displayOrder)=>({entryId:e.id,imageUrl:image.url,cloudinaryPublicId:image.publicId,displayOrder})));return e});res.status(201).json({id:entry.id,status:"pending",message:"Your entry has been submitted and is waiting for verification."})}catch(e:any){res.status(e?.code==="23505"?409:502).json({error:e?.code==="23505"?"An entry for this resident already exists.":"Unable to submit your entry."})}}));
router.post("/competitions/:id/vote",async(req,res)=>{const competitionId=id(req.params.id),entryId=id(req.body?.entryId);if(!competitionId||!entryId){res.status(400).json({error:"Invalid vote request."});return;}if(!secret){res.status(503).json({error:"Voting security is not configured."});return;}const {ip,ipHash,userAgentHash}=reqHashes(req);const since=new Date(Date.now()-600000);const [{count:tries}]=await db.select({count:sql<number>`COUNT(*)::int`}).from(competitionSecurityAttemptsTable).where(and(eq(competitionSecurityAttemptsTable.ipHash,ipHash),gte(competitionSecurityAttemptsTable.createdAt,since)));if(tries>=30){await attempt(req,competitionId,entryId,"blocked_rate_limit");res.status(429).json({error:"Too many requests. Please try again later."});return;}const c=(await db.select().from(competitionsTable).where(eq(competitionsTable.id,competitionId)).limit(1))[0];if(!c||!open(c,"voting")){res.status(403).json({error:"Voting has ended."});return;}const e=(await db.select({id:competitionEntriesTable.id}).from(competitionEntriesTable).where(and(eq(competitionEntriesTable.id,entryId),eq(competitionEntriesTable.competitionId,competitionId),eq(competitionEntriesTable.status,"approved"))).limit(1))[0];if(!e){res.status(404).json({error:"This entry is not eligible for voting."});return;}if(!await captcha(String(req.body?.turnstileToken||""),ip)){await attempt(req,competitionId,entryId,"failed_captcha");res.status(400).json({error:"Captcha verification failed. Please try again."});return;}const raw=req.cookies?.ms_competition_voter||randomBytes(32).toString("base64url"),voterHash=createHmac("sha256",secret).update(`voter:${raw}`).digest("hex");const [{count:networkVotes}]=await db.select({count:sql<number>`COUNT(*)::int`}).from(competitionVotesTable).where(and(eq(competitionVotesTable.competitionId,competitionId),eq(competitionVotesTable.ipHash,ipHash),gte(competitionVotesTable.createdAt,since)));try{await db.insert(competitionVotesTable).values({competitionId,entryId,voterHash,ipHash,userAgentHash,riskStatus:networkVotes>=8?"suspicious":"normal",riskScore:networkVotes>=8?50:0,riskMetadata:{networkVotesLastTenMinutes:networkVotes}});if(!req.cookies?.ms_competition_voter)res.cookie("ms_competition_voter",raw,{httpOnly:true,secure:process.env.NODE_ENV==="production",sameSite:"lax",maxAge:34560000000,path:"/api/competitions"});await attempt(req,competitionId,entryId,"accepted");res.status(201).json({message:"Your vote has been recorded successfully!"})}catch(err:any){if(err?.code==="23505"){await attempt(req,competitionId,entryId,"duplicate");res.status(409).json({error:"You have already voted in this competition."});return;}res.status(500).json({error:"Unable to record your vote."})}});
router.get("/admin/competitions",requireRole("Super Admin","Admin"),async(_q,res)=>res.json(await db.select().from(competitionsTable).orderBy(desc(competitionsTable.createdAt))));
router.get("/admin/competitions/:id/entries",requireRole("Super Admin","Admin"),async(req,res)=>{const competitionId=id(req.params.id);if(!competitionId){res.status(400).json({error:"Invalid competition id"});return;}const rows=await db.select({id:competitionEntriesTable.id,title:competitionEntriesTable.title,description:competitionEntriesTable.description,status:competitionEntriesTable.status,reviewNote:competitionEntriesTable.reviewNote,createdAt:competitionEntriesTable.createdAt,updatedAt:competitionEntriesTable.updatedAt,residentName:residentsTable.fullName,flatNo:residentsTable.flatNo,buildingName:buildingsTable.buildingName,wingName:wingsTable.wingName,imageUrl:competitionEntryImagesTable.imageUrl,displayOrder:competitionEntryImagesTable.displayOrder,votes:sql<number>`COUNT(${competitionVotesTable.id})::int`}).from(competitionEntriesTable).innerJoin(residentsTable,eq(competitionEntriesTable.residentId,residentsTable.id)).innerJoin(buildingsTable,eq(residentsTable.buildingId,buildingsTable.id)).leftJoin(wingsTable,eq(residentsTable.wingId,wingsTable.id)).leftJoin(competitionEntryImagesTable,eq(competitionEntryImagesTable.entryId,competitionEntriesTable.id)).leftJoin(competitionVotesTable,eq(competitionVotesTable.entryId,competitionEntriesTable.id)).where(eq(competitionEntriesTable.competitionId,competitionId)).groupBy(competitionEntriesTable.id,residentsTable.fullName,residentsTable.flatNo,buildingsTable.buildingName,wingsTable.wingName,competitionEntryImagesTable.id).orderBy(desc(competitionEntriesTable.createdAt));const map=new Map<number,any>();rows.forEach(r=>{const e=map.get(r.id)||{...r,images:[]};delete e.imageUrl;delete e.displayOrder;if(r.imageUrl)e.images.push({imageUrl:r.imageUrl,displayOrder:r.displayOrder});map.set(r.id,e)});res.json([...map.values()])});
router.post("/admin/competitions",requireRole("Super Admin","Admin"),async(req:any,res)=>{const p=settingsSchema.safeParse(req.body);if(!p.success){res.status(400).json({error:"Invalid competition settings."});return;}const d=p.data,[c]=await db.insert(competitionsTable).values({...d,date:asDate(d.date)||new Date(),registrationStart:asDate(d.registrationStart),registrationEnd:asDate(d.registrationEnd),votingStart:asDate(d.votingStart),votingEnd:asDate(d.votingEnd),resultsPublished:d.resultsPublished?1:0,createdByAdminId:req.admin.id}).returning();res.status(201).json(c)});
router.patch("/admin/competition-entries/:id/:decision",requireRole("Super Admin","Admin"),async(req:any,res)=>{const entryId=id(req.params.id),decision=req.params.decision;if(!entryId||!["approve","reject"].includes(decision)){res.status(400).json({error:"Invalid entry action"});return;}const [e]=await db.update(competitionEntriesTable).set({status:decision==="approve"?"approved":"rejected",reviewedByAdminId:req.admin.id,reviewNote:typeof req.body?.reviewNote==="string"?req.body.reviewNote.trim().slice(0,1000):null}).where(eq(competitionEntriesTable.id,entryId)).returning();if(!e){res.status(404).json({error:"Entry not found"});return;}res.json(e)});
router.get("/admin/competitions/:id/results",requireRole("Super Admin","Admin"),async(req,res)=>{const competitionId=id(req.params.id);if(!competitionId){res.status(400).json({error:"Invalid competition id"});return;}res.json(await db.select({entryId:competitionEntriesTable.id,title:competitionEntriesTable.title,participant:residentsTable.fullName,votes:sql<number>`COUNT(${competitionVotesTable.id})::int`}).from(competitionEntriesTable).innerJoin(residentsTable,eq(competitionEntriesTable.residentId,residentsTable.id)).leftJoin(competitionVotesTable,eq(competitionVotesTable.entryId,competitionEntriesTable.id)).where(and(eq(competitionEntriesTable.competitionId,competitionId),eq(competitionEntriesTable.status,"approved"))).groupBy(competitionEntriesTable.id,residentsTable.fullName).orderBy(desc(sql`COUNT(${competitionVotesTable.id})`)))});
export default router;
