import { useMemo, useRef, useState } from "react";
import { ArrowLeft, Check, Copy, Film, Image as ImageIcon, Instagram, Link as LinkIcon, Share2, Sparkles, Trophy, Upload, Video } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { useLocation, useRoute } from "wouter";
import { toast } from "sonner";
import SEO from "@/components/SEO";
import { Button } from "@/components/ui/button";
import { getApiUrl } from "@/lib/utils";

type Category = "photography" | "reels" | "videography";
type Competition = { id: number; name: string; description: string; registrationOpen: boolean; status: string };
const categories: { id: Category; label: string; icon: typeof ImageIcon; copy: string }[] = [
  { id: "photography", label: "Photography", icon: ImageIcon, copy: "Freeze a moment from the Aagman Sohala." },
  { id: "reels", label: "Reels", icon: Film, copy: "Share your best Instagram Reel." },
  { id: "videography", label: "Videography", icon: Video, copy: "Tell the story in motion." },
];
const validMobile = (value: string) => /^(?:\+91|91)?[6-9]\d{9}$/.test(value.replace(/[\s-]/g, ""));
const validInstagram = (value: string) => /^[A-Za-z0-9._]{1,30}$/.test(value.replace(/^@/, ""));
const validReel = (value: string) => /^https?:\/\/(www\.)?instagram\.com\/(reel|reels)\/[A-Za-z0-9_-]+\/?(?:\?.*)?$/i.test(value);

export default function CompetitionRegister() {
  const [, params] = useRoute("/competitions/:id/register");
  const [, setLocation] = useLocation();
  const fileRef = useRef<HTMLInputElement>(null);
  const [category, setCategory] = useState<Category | "">("");
  const [form, setForm] = useState({ fullName: "", mobile: "", email: "", instagramUsername: "", title: "", submissionUrl: "" });
  const [file, setFile] = useState<File | null>(null);
  const [preview, setPreview] = useState("");
  const [step, setStep] = useState<"form" | "review" | "success">("form");
  const [submitting, setSubmitting] = useState(false);
  const [entryId, setEntryId] = useState("");
  const api = getApiUrl();
  const competitionQuery = useQuery<Competition>({ queryKey: ["competition-register", params?.id], enabled: !!params?.id, queryFn: async () => { const r = await fetch(`${api}/api/competitions/${params!.id}`); if (!r.ok) throw new Error("Competition not found"); return r.json(); } });
  const selected = categories.find((item) => item.id === category);
  const submissionLabel = useMemo(() => file?.name || form.submissionUrl || "Not selected", [file, form.submissionUrl]);
  const chooseCategory = (next: Category) => { setCategory(next); setFile(null); setPreview(""); setForm((current) => ({ ...current, submissionUrl: "" })); if (fileRef.current) fileRef.current.value = ""; };
  const onFile = (next: File | undefined) => { if (!next || !category) return; const isImage = category === "photography" && ["image/jpeg", "image/png", "image/webp"].includes(next.type); const isVideo = category === "videography" && ["video/mp4", "video/quicktime", "video/webm"].includes(next.type); const max = category === "photography" ? 5 : 50; if (!(isImage || isVideo)) { toast.error(category === "photography" ? "Please choose a JPG, PNG, or WebP image." : "Please choose an MP4, MOV, or WebM video."); return; } if (next.size > max * 1024 * 1024) { toast.error(`File must be smaller than ${max} MB.`); return; } setFile(next); setPreview(isImage ? URL.createObjectURL(next) : ""); };
  const validate = () => { if (form.fullName.trim().length < 2) return "Please enter your full name."; if (!validMobile(form.mobile)) return "Please enter a valid Indian mobile number."; if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.email)) return "Please enter a valid email address."; if (!validInstagram(form.instagramUsername)) return "Please enter a valid Instagram username."; if (!category) return "Select a competition category to continue."; if (category === "reels" && !validReel(form.submissionUrl)) return "Please enter a valid Instagram Reel URL."; if (category !== "reels" && !file) return "Please select your entry file."; return ""; };
  const submit = async () => { const error = validate(); if (error) { toast.error(error); return; } setSubmitting(true); try { const data = new FormData(); Object.entries({ ...form, category, fullName: form.fullName.trim(), mobile: form.mobile.trim(), instagramUsername: form.instagramUsername.trim() }).forEach(([key, value]) => data.append(key, value)); if (file) data.append("submission", file); const response = await fetch(`${api}/api/competitions/${params!.id}/register-public`, { method: "POST", body: data }); const result = await response.json().catch(() => ({})); if (!response.ok) throw new Error(result.error || "Something went wrong. Please try again."); setEntryId(result.entryId); setStep("success"); } catch (error) { toast.error(error instanceof Error ? error.message : "Something went wrong. Please try again."); } finally { setSubmitting(false); } };
  const share = async () => {
        const url = window.location.href; const text = "Join the Medtiya Mitra Mandal Aagman Sohala 2026 Competition!"; if (navigator.share) await navigator.share({ title: "Aagman Sohala 2026 Competition", text, url }); else { await navigator.clipboard.writeText(url); toast.success("Competition link copied."); }
      };
        if (competitionQuery.isLoading) return <main className="min-h-screen bg-[var(--page-bg)] px-4 pt-32 text-center text-muted-foreground">Loading registration...</main>;
  if (competitionQuery.isError || !competitionQuery.data) return <main className="min-h-screen bg-[var(--page-bg)] px-4 pt-32 text-center">Competition not found.</main>;
  const competition = competitionQuery.data;
  return <><SEO title="Aagman Sohala 2026 Registration | Meditiya Sathi" description="Submit your entry for the Medtiya Mitra Mandal Aagman Sohala 2026 competition." path={`/competitions/${competition.id}/register`} /><main className="min-h-screen bg-[var(--page-bg)] px-4 pb-16 pt-24 sm:px-6"><div className="mx-auto max-w-3xl">
    {step !== "success" && <button onClick={() => setLocation(`/competitions/${competition.id}`)} className="mb-6 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-primary"><ArrowLeft className="h-4 w-4" /> Back to competition</button>}
    {step === "success" ? <section className="rounded-3xl border-amber-400/30 bg-card p-6 text-center shadow-2xl shadow-amber-950/20 sm:p-12"><div className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-amber-400/15 text-amber-300"><Check className="h-8 w-8" /></div><p className="mt-6 text-xs font-bold uppercase tracking-[.25em] text-amber-300">Registration Successful!</p><h1 className="mt-3 font-serif text-3xl font-bold sm:text-4xl">Thank you for participating</h1><p className="mx-auto mt-3 max-w-md text-muted-foreground">Thank you for participating in the Medtiya Mitra Mandal Aagman Sohala 2026 Competition.</p><div className="mt-8 rounded-2xl border-amber-400/30 bg-amber-400/10 p-5"><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-300">Your Entry ID</p><p className="mt-2 break-all font-mono text-2xl font-bold text-amber-100 sm:text-3xl">{entryId}</p><p className="mt-2 text-xs text-muted-foreground">Please save your Entry ID for future communication.</p></div><div className="mt-6 flex-col gap-3 sm:flex-row sm:justify-center"><Button variant="outline" onClick={() => { navigator.clipboard.writeText(entryId); toast.success("Entry ID copied."); }}><Copy /> Copy Entry ID</Button><Button variant="outline" asChild><a href="https://www.instagram.com/" target="_blank" rel="noreferrer"><Instagram /> Follow Instagram</a></Button><Button variant="outline" onClick={() => setLocation("/")}>Visit Website</Button><Button onClick={share}><Share2 /> Share Competition</Button></div></section> : <>
      <header className="relative overflow-hidden rounded-3xl border-amber-400/20 bg-gradient-to-br from-zinc-950 via-zinc-900 to-amber-950/40 p-6 shadow-2xl sm:p-10"><div className="absolute -right-10 -top-10 h-40 w-40 rounded-full bg-amber-400/10 blur-3xl" /><Sparkles className="h-7 w-7 text-amber-300" /><p className="mt-5 text-xs font-bold uppercase tracking-[.25em] text-amber-300">मेड़तिया मित्र मंडळ</p><h1 className="mt-2 font-serif text-3xl font-bold text-white sm:text-5xl">आगमन सोहळा २०२६</h1><p className="mt-3 text-lg font-semibold text-amber-100">Competition Registration & Entry Submission</p><p className="mt-4 max-w-xl text-sm leading-6 text-zinc-300">Capture the moment. Create the story. Be a part of Medtiya Mitra Mandal Aagman Sohala 2026.</p></header>
      <form onSubmit={(event) => { event.preventDefault(); if (step === "form") { const error = validate(); if (error) toast.error(error); else setStep("review"); } else submit(); }} className="mt-6 space-y-5">
        <section className="rounded-2xl border bg-card p-5 shadow-sm sm:p-7"><p className="text-xs font-bold uppercase tracking-[.2em] text-primary">Participant Information</p><div className="mt-5 grid gap-4 sm:grid-cols-2">{[["fullName","Full Name *","text","Your full name"],["mobile","WhatsApp / Mobile Number *","tel","+91 9876543210"],["email","Email Address *","email","you@example.com"],["instagramUsername","Instagram Username *","text","@yourusername"]].map(([key,label,type,placeholder]) => <label key={key} className="block text-sm font-semibold">{label}<input required aria-label={label} type={type} value={form[key as keyof typeof form]} onChange={(e) => setForm({ ...form, [key]: e.target.value })} placeholder={placeholder} className="mt-2 min-h-12 w-full rounded-xl border bg-background px-4 font-normal outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/20" /></label>)}</div></section>
        <section className="rounded-2xl border bg-card p-5 shadow-sm sm:p-7"><p className="text-xs font-bold uppercase tracking-[.2em] text-primary">Competition Category *</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{categories.map(({ id, label, icon: Icon, copy }) => <button type="button" key={id} onClick={() => chooseCategory(id)} aria-pressed={category === id} className={`min-h-32 rounded-2xl border p-4 text-left transition ${category === id ? "border-amber-300 bg-amber-400/15 text-amber-100 ring-2 ring-amber-300/40" : "bg-background hover:border-primary/60"}`}><Icon className="h-6 w-6 text-amber-300" /><span className="mt-3 block font-bold">{label}</span><span className="mt-1 block text-xs font-normal text-muted-foreground">{copy}</span></button>)}</div></section>
        <section className="rounded-2xl border bg-card p-5 shadow-sm sm:p-7"><p className="text-xs font-bold uppercase tracking-[.2em] text-primary">{selected ? `${selected.label} Entry` : "Submission"}</p>{!selected ? <p className="mt-4 rounded-xl border-dashed p-6 text-center text-sm text-muted-foreground">Select a competition category to continue.</p> : <div className="mt-4 space-y-4"><label className="block text-sm font-semibold">Entry Title / Caption <span className="font-normal text-muted-foreground">(optional)</span><input value={form.title} maxLength={150} onChange={(e) => setForm({ ...form, title: e.target.value })} className="mt-2 min-h-12 w-full rounded-xl border bg-background px-4 font-normal outline-none focus:border-primary focus:ring-2 focus:ring-primary/20" /></label>{category === "reels" ? <label className="block text-sm font-semibold"><LinkIcon className="mr-2 inline h-4 w-4 text-amber-300" />Instagram Reel URL *<input required value={form.submissionUrl} onChange={(e) => setForm({ ...form, submissionUrl: e.target.value })} placeholder="https://www.instagram.com/reel/..." className="mt-2 min-h-12 w-full rounded-xl border bg-background px-4 font-normal outline-none focus:border-primary focus:ring-2 focus:ring-primary/20" /></label> : <div><span className="text-sm font-semibold">{category === "photography" ? "Photography Entry Image *" : "Video Submission *"}</span><input ref={fileRef} required type="file" accept={category === "photography" ? "image/jpeg,image/png,image/webp" : "video/mp4,video/quicktime,video/webm"} onChange={(e) => onFile(e.target.files?.[0])} className="mt-2 block min-h-12 w-full cursor-pointer rounded-xl border bg-background p-2 text-sm file:mr-3 file:min-h-9 file:rounded-lg file:border-0 file:bg-primary file:px-3 file:font-semibold file:text-primary-foreground" />{preview && <img src={preview} alt="Selected entry preview" className="mt-4 aspect-video w-full rounded-xl object-cover" />}{file && <p className="mt-3 flex items-center gap-2 text-sm text-muted-foreground"><Upload className="h-4 w-4 text-primary" />{file.name}<button type="button" onClick={() => { setFile(null); setPreview(""); if (fileRef.current) fileRef.current.value = ""; }} className="ml-auto text-primary underline">Remove</button></p>}</div>}</div>}</section>
        {step === "review" && <section className="rounded-2xl border-amber-400/30 bg-amber-400/5 p-5 sm:p-7"><p className="text-xs font-bold uppercase tracking-[.2em] text-amber-300">Review Your Entry</p><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><div><dt className="text-muted-foreground">Participant</dt><dd className="font-semibold">{form.fullName}</dd></div><div><dt className="text-muted-foreground">WhatsApp</dt><dd className="font-semibold">{form.mobile}</dd></div><div><dt className="text-muted-foreground">Email</dt><dd className="font-semibold">{form.email}</dd></div><div><dt className="text-muted-foreground">Instagram</dt><dd className="font-semibold">@{form.instagramUsername.replace(/^@/, "")}</dd></div><div><dt className="text-muted-foreground">Category</dt><dd className="font-semibold">{selected?.label}</dd></div><div><dt className="text-muted-foreground">Submission</dt><dd className="break-all font-semibold">{submissionLabel}</dd></div></dl><button type="button" onClick={() => setStep("form")} className="mt-5 text-sm font-bold text-primary underline">Edit</button></section>}
        <Button type="submit" disabled={submitting || !category} size="lg" className="min-h-14 w-full text-base font-bold shadow-lg shadow-primary/20">{submitting ? "Submitting registration..." : step === "review" ? <><Trophy /> Submit Competition Entry</> : "Review Your Entry"}</Button>
      </form></>}
  </div></main></>;
}
