import { Link } from "wouter";
import { CalendarDays, Clock3, MapPin, ArrowRight, AlertCircle } from "lucide-react";
import { useListEvents } from "@workspace/api-client-react";
import { eventDateTime, optimizedEventImage, statusLabel } from "@/lib/event-utils";

function EventCard({ event, priority = false }: { event: any; priority?: boolean }) {
  const { date, time } = eventDateTime(event.date, event.eventTime);
  const statusClass = event.status === "cancelled" ? "bg-destructive/10 text-destructive" : event.status === "completed" ? "bg-muted text-muted-foreground" : "bg-primary/15 text-primary";
  return <article className="group overflow-hidden rounded-2xl border bg-card shadow-sm transition-shadow hover:shadow-lg">
    <div className="relative aspect-[4/3] bg-muted">{event.imageUrl ? <img src={optimizedEventImage(event.imageUrl, 720)} alt={event.title} width="720" height="540" loading={priority ? "eager" : "lazy"} decoding="async" className="h-full w-full object-cover" /> : <CalendarDays className="absolute inset-0 m-auto h-12 w-12 text-muted-foreground/40" />}<span className={`absolute left-3 top-3 rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider ${statusClass}`}>{statusLabel(event.status)}</span></div>
    <div className="space-y-4 p-5"><h2 className="font-serif text-2xl font-semibold leading-tight text-foreground">{event.title}</h2><div className="space-y-2 text-sm text-muted-foreground"><p className="flex items-center gap-2"><CalendarDays className="h-4 w-4 text-primary" />{date}</p><p className="flex items-center gap-2"><Clock3 className="h-4 w-4 text-primary" />{time}</p><p className="flex items-center gap-2"><MapPin className="h-4 w-4 text-primary" />{event.location}</p></div><p className="line-clamp-2 text-sm leading-6 text-muted-foreground">{event.description}</p><Link href={`/events/${event.id}`} className="inline-flex items-center gap-2 text-sm font-semibold text-primary transition-colors hover:text-primary/75">View Event <ArrowRight className="h-4 w-4" /></Link></div>
  </article>;
}

export default function Events() {
  const { data: allEvents, isLoading, isError } = useListEvents({ status: "all", limit: 100 });
  const now = new Date(); const events = allEvents ?? [];
  const upcoming = events.filter((event) => event.status === "upcoming" && new Date(event.date) >= now).sort((a, b) => +new Date(a.date) - +new Date(b.date));
  const past = events.filter((event) => event.status !== "upcoming" || new Date(event.date) < now).sort((a, b) => +new Date(b.date) - +new Date(a.date));
  return <main className="min-h-screen bg-[var(--page-bg)] pb-16 pt-28 text-foreground sm:pt-32"><div className="mx-auto max-w-6xl px-4 sm:px-6"><header className="mb-10 max-w-2xl"><p className="mb-3 text-xs font-bold uppercase tracking-[0.22em] text-primary">Meditiya Nagar</p><h1 className="font-serif text-4xl font-semibold sm:text-5xl">Community Events</h1><p className="mt-3 leading-7 text-muted-foreground">Discover celebrations, activities, and moments that bring our community together.</p></header>{isLoading && <p className="py-16 text-center text-muted-foreground">Loading events...</p>}{isError && <div className="rounded-xl border border-destructive/30 bg-destructive/5 p-6 text-center"><AlertCircle className="mx-auto mb-3 h-6 w-6 text-destructive" /><p className="font-semibold">Unable to load events.</p><p className="mt-1 text-sm text-muted-foreground">Please try again.</p></div>}{!isLoading && !isError && <div className="space-y-14"><section><h2 className="mb-5 font-serif text-2xl font-semibold">Upcoming Events</h2>{upcoming.length ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{upcoming.map((event, index) => <EventCard key={event.id} event={event} priority={index === 0} />)}</div> : <div className="rounded-xl border bg-card p-8 text-center"><p className="font-semibold">No upcoming events yet.</p><p className="mt-1 text-sm text-muted-foreground">Check back soon for community activities.</p></div>}</section><section><h2 className="mb-5 font-serif text-2xl font-semibold">Past Events</h2>{past.length ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{past.map((event) => <EventCard key={event.id} event={event} />)}</div> : <p className="rounded-xl border bg-card p-8 text-center text-muted-foreground">No past events available.</p>}</section></div>}</div></main>;
}
