import { useEffect, useState } from "react";
import { Link, useRoute } from "wouter";
import { ArrowLeft, ChevronLeft, ChevronRight, Image as ImageIcon, X } from "lucide-react";
import { getApiUrl } from "@/lib/utils";
import SEO from "@/components/SEO";

type Photo = { id: number; imageUrl: string; title?: string | null; description?: string | null; caption?: string | null };
type Album = { id: number; title: string; slug: string; description?: string | null; coverImageUrl?: string | null; photoCount: number };
export default function GalleryAlbum() {
  const [, params] = useRoute("/gallery/:slug");
  const [data, setData] = useState<{ album: Album; photos: Photo[] } | null>(null);
  const [active, setActive] = useState<number | null>(null);
  useEffect(() => { let cancelled = false; if (params?.slug) fetch(`${getApiUrl()}/api/gallery/albums/${encodeURIComponent(params.slug)}`).then(async (response) => { if (!response.ok) throw new Error(response.status === 404 ? "Album not found" : "Unable to load album"); return response.json(); }).then((value) => { if (!cancelled) setData(value); }).catch(() => { if (!cancelled) setData(null); }); return () => { cancelled = true; }; }, [params?.slug]);
  if (!data) return <><SEO title="Gallery Album | Meditiya Sathi" description="Browse community photos and memories from Medtiya Nagar." path={`/gallery/${params?.slug || ""}`} /><main className="min-h-screen bg-background px-4 py-24 text-center text-muted-foreground">Unable to load album. <Link href="/gallery" className="text-primary">Back to gallery</Link></main></>;
  const photo = active === null ? null : data.photos[active];
  const description = data.album.description || `Browse photos and memories from ${data.album.title} at Medtiya Nagar.`;
  return <><SEO title={`${data.album.title} | Meditiya Sathi`} description={description} path={`/gallery/${data.album.slug}`} ogType="article" /><main className="min-h-screen bg-background px-4 pb-20 pt-12"><div className="mx-auto max-w-6xl"><Link href="/gallery" className="inline-flex items-center gap-2 text-sm text-primary"><ArrowLeft className="h-4 w-4" /> Back to gallery</Link><header className="py-10">{data.album.coverImageUrl && <div className="mb-8 overflow-hidden rounded-3xl border-border bg-muted"><img src={data.album.coverImageUrl} alt={`Photos from ${data.album.title} in Medtiya Nagar`} className="max-h-[28rem] w-full object-cover" /></div>}<p className="text-xs font-semibold uppercase tracking-[.25em] text-primary/80">Community memories</p><h1 className="mt-3 font-serif text-4xl font-bold text-foreground md:text-5xl">{data.album.title}</h1>{data.album.description && <p className="mt-4 max-w-2xl text-muted-foreground">{data.album.description}</p>}<p className="mt-3 text-sm text-muted-foreground">{data.photos.length} photos</p></header>{data.photos.length ? <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4">{data.photos.map((item, index) => <button key={item.id} onClick={() => setActive(index)} className="group aspect-square overflow-hidden rounded-2xl border-border bg-muted text-left"><img src={item.imageUrl} alt={item.title || item.caption || "Gallery photo"} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" loading="lazy" /></button>)}</div> : <div className="rounded-3xl border-border bg-muted/20 py-20 text-center text-muted-foreground"><ImageIcon className="mx-auto mb-3 h-12 w-12 opacity-40" />No published photos in this album.</div>}</div>{photo && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/90 p-4" onClick={() => setActive(null)}><button className="absolute right-5 top-5 rounded-full bg-white/10 p-3 text-white" onClick={() => setActive(null)}><X /></button><button className="absolute left-3 rounded-full bg-white/10 p-3 text-white sm:left-8" onClick={(e) => { e.stopPropagation(); setActive((active! - 1 + data.photos.length) % data.photos.length); }}><ChevronLeft /></button><img src={photo.imageUrl} alt={photo.title || "Gallery photo"} className="max-h-[85vh] max-w-[90vw] rounded-xl object-contain" onClick={(e) => e.stopPropagation()} /><button className="absolute right-3 rounded-full bg-white/10 p-3 text-white sm:right-8" onClick={(e) => { e.stopPropagation(); setActive((active! + 1) % data.photos.length); }}><ChevronRight /></button></div>}</main></>;
}
