import { useEffect, useState } from "react";
import { CalendarClock, Check, Edit3, Loader2, Plus, Power, X } from "lucide-react";
import { toast } from "sonner";
import { getApiUrl } from "@/lib/utils";
import { useAdminAuth } from "@/lib/AdminAuthContext";

type Countdown = { id: number; name: string; targetAt: string; description: string | null; enabled: boolean; displayOnHomepage: boolean; displayOnPublicPage: boolean };
type Form = { name: string; targetDate: string; targetTime: string; description: string; enabled: boolean; displayOnHomepage: boolean; displayOnPublicPage: boolean };
const empty: Form = { name: "", targetDate: "", targetTime: "", description: "", enabled: true, displayOnHomepage: false, displayOnPublicPage: false };
function headers() { const raw = localStorage.getItem("admin_auth"); const token = raw ? JSON.parse(raw)?.token : null; return { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) }; }
function dateParts(value: string) { const date = new Date(value); return { date: new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeZone: "Asia/Kolkata" }).format(date), time: new Intl.DateTimeFormat("en-IN", { timeStyle: "short", timeZone: "Asia/Kolkata" }).format(date) }; }
function state(value: string, enabled: boolean) { if (!enabled) return ["OFF", "text-zinc-400 bg-zinc-500/10"]; if (new Date(value).getTime() <= Date.now()) return ["LIVE", "text-emerald-300 bg-emerald-500/10"]; return ["UPCOMING", "text-amber-300 bg-amber-500/10"]; }

export default function FestivalCountdowns() {
  const { isVolunteer } = useAdminAuth();
  const [items, setItems] = useState<Countdown[]>([]); const [form, setForm] = useState<Form>(empty); const [editing, setEditing] = useState<Countdown | null>(null); const [showForm, setShowForm] = useState(false); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const load = async () => {
    setLoading(true); setError(""); try { const response = await fetch(`${getApiUrl()}/api/admin/festival-countdowns`, { headers: headers() }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Failed to load countdowns."); setItems(data.countdowns || []); } catch (e: any) { setError(e.message); } finally { setLoading(false); }
  };
  useEffect(() => { if (!isVolunteer) void load(); }, [isVolunteer]);
  const open = (item?: Countdown) => { setEditing(item || null); setForm(item ? { name: item.name, targetDate: new Date(item.targetAt).toLocaleDateString("en-CA", { timeZone: "Asia/Kolkata" }), targetTime: new Date(item.targetAt).toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit", timeZone: "Asia/Kolkata" }), description: item.description || "", enabled: item.enabled, displayOnHomepage: item.displayOnHomepage, displayOnPublicPage: item.displayOnPublicPage } : { ...empty }); setShowForm(true); };
  const save = async (event: React.FormEvent) => {
    event.preventDefault(); if (!form.name.trim() || !form.targetDate || !form.targetTime) { toast.error("Name, date and time are required"); return; } setSaving(true); try { const response = await fetch(`${getApiUrl()}/api/admin/festival-countdowns${editing ? `/${editing.id}` : ""}`, { method: editing ? "PATCH" : "POST", headers: headers(), body: JSON.stringify(form) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Could not save countdown"); toast.success(editing ? "Countdown updated" : "Countdown created"); setEditing(null); setForm(empty); setShowForm(false); await load(); } catch (e: any) { toast.error(e.message); } finally { setSaving(false); }
  };
    const disable = async (item: Countdown) => { if (!window.confirm(`Delete the countdown for ${item.name}?`)) return; const response = await fetch(`${getApiUrl()}/api/admin/festival-countdowns/${item.id}`, { method: "DELETE", headers: headers() }); if (response.ok) { toast.success("Countdown deleted"); await load(); } else toast.error("Could not delete countdown"); };
  if (isVolunteer) return <div className="p-8 text-white">You do not have access to countdown management.</div>;
  return <main className="min-h-screen bg-[#080808] px-4 py-8 text-white sm:px-8"><div className="mx-auto max-w-6xl"><div className="mb-8 flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.25em] text-amber-300/70">Administration</p><h1 className="mt-2 text-3xl font-semibold">Festival Countdown</h1><p className="mt-2 text-sm text-white/45">Configure independent celebration timers for the public website.</p></div><button onClick={() => open()} className="inline-flex items-center justify-center gap-2 rounded-xl bg-amber-300 px-4 py-3 text-sm font-semibold text-black hover:bg-amber-200"><Plus className="h-4 w-4" />Add Countdown</button></div>
  {error && <div className="mb-5 rounded-xl border-red-400/20 bg-red-400/10 p-4 text-sm text-red-200">{error} <button className="ml-2 underline" onClick={() => void load()}>Retry</button></div>}{loading ? <div className="grid gap-3">{[1,2,3].map((x) => <div key={x} className="h-24 animate-pulse rounded-xl border-white/10 bg-white/[.04]" />)}</div> : items.length === 0 ? <div className="rounded-xl border-dashed border-white/15 p-12 text-center text-white/55"><CalendarClock className="mx-auto mb-3 h-8 w-8 text-amber-300/60" /><p>No festival countdowns configured.</p><button onClick={() => open()} className="mt-5 text-sm font-semibold text-amber-300">Add your first countdown</button></div> : <div className="overflow-hidden rounded-xl border-white/10 bg-white/[.035]"><div className="hidden grid-cols-[1.4fr_1fr_.8fr_.8fr_120px] gap-4 border-b border-white/10 px-5 py-3 text-[10px] font-semibold uppercase tracking-wider text-white/40 md:grid"><span>Countdown</span><span>Target</span><span>Status</span><span>Visibility</span><span /></div>{items.map((item) => { const [label, style] = state(item.targetAt, item.enabled); const parts = dateParts(item.targetAt); return <div key={item.id} className="grid gap-3 border-b border-white/10 px-4 py-4 last:border-0 md:grid-cols-[1.4fr_1fr_.8fr_.8fr_120px] md:items-center md:gap-4 md:px-5"><div><p className="font-semibold">{item.name}</p><p className="mt-1 text-xs text-white/40">{item.description}</p></div><div className="text-sm text-white/70">{parts.date}<span className="mx-1 text-white/25">•</span>{parts.time}</div><span className={`w-fit rounded-full px-2.5 py-1 text-[10px] font-bold tracking-wider ${style}`}>{label}</span><div className="flex gap-2 text-xs text-white/50"><span className={item.displayOnHomepage ? "text-amber-300" : ""}>Homepage</span><span className={item.displayOnPublicPage ? "text-amber-300" : ""}>Public</span></div><div className="flex gap-2"><button title="Edit countdown" onClick={() => open(item)} className="rounded-lg p-2 text-white/55 hover:bg-white/10 hover:text-amber-300"><Edit3 className="h-4 w-4" /></button>{item.enabled && <button title="Disable countdown" onClick={() => void disable(item)} className="rounded-lg p-2 text-white/55 hover:bg-red-400/10 hover:text-red-300"><Power className="h-4 w-4" /></button>}</div></div>; })}</div>}
  {showForm && <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/70 p-0 sm:items-center sm:p-4"><form onSubmit={save} className="max-h-[95vh] w-full max-w-xl overflow-y-auto rounded-t-2xl border-white/10 bg-[#151515] p-5 shadow-2xl sm:rounded-2xl sm:p-7"><div className="mb-6 flex items-center justify-between"><h2 className="text-xl font-semibold">{editing ? "Edit Countdown" : "Add Countdown"}</h2><button type="button" onClick={() => { setEditing(null); setForm(empty); setShowForm(false); }}><X className="h-5 w-5 text-white/50" /></button></div><label className="mb-4 block text-sm text-white/70">Countdown Name<input required value={form.name} placeholder="Ganesh Utsav 2026" onChange={(e) => setForm({ ...form, name: e.target.value })} className="mt-2 w-full rounded-lg border-white/10 bg-black/30 p-3 text-white" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm text-white/70">Target date<input required type="date" value={form.targetDate} onChange={(e) => setForm({ ...form, targetDate: e.target.value })} className="mt-2 w-full rounded-lg border-white/10 bg-black/30 p-3 text-white" /></label><label className="text-sm text-white/70">Target time (India)<input required type="time" value={form.targetTime} onChange={(e) => setForm({ ...form, targetTime: e.target.value })} className="mt-2 w-full rounded-lg border-white/10 bg-black/30 p-3 text-white" /></label></div><label className="mt-4 block text-sm text-white/70">Description<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="mt-2 min-h-20 w-full rounded-lg border-white/10 bg-black/30 p-3 text-white" /></label><div className="mt-5 grid gap-3 text-sm text-white/70 sm:grid-cols-2">{([["enabled","Enabled"],["displayOnHomepage","Show on Homepage"],["displayOnPublicPage","Show on Public Countdown Page"]] as const).map(([key, label]) => <label key={key} className="flex items-center gap-3"><input type="checkbox" checked={form[key as keyof Form] as boolean} onChange={(e) => setForm({ ...form, [key]: e.target.checked })} className="h-4 w-4 accent-amber-300" />{label}</label>)}</div><button disabled={saving} className="mt-7 flex w-full items-center justify-center gap-2 rounded-xl bg-amber-300 py-3 font-semibold text-black disabled:opacity-50">{saving && <Loader2 className="h-4 w-4 animate-spin" />}{saving ? "Saving..." : <><Check className="h-4 w-4" />Save Countdown</>}</button></form></div>}</div></main>;
}
