import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { FolderOpen, Plus, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { getApiUrl } from "@/lib/utils";
import { useAdminAuth } from "@/lib/AdminAuthContext";

type Album = { id: number; title: string; description?: string | null; slug: string; isPublished: boolean; photoCount: number; coverImageUrl?: string | null; updatedAt?: string };
function headers(): Record<string, string> { const raw = localStorage.getItem("admin_auth"); const token = raw ? JSON.parse(raw)?.token : null; return token ? { Authorization: `Bearer ${token}` } : {}; }
export default function AdminGalleryAlbums() {
  const { isSuperAdmin, isVolunteer } = useAdminAuth(); const [, navigate] = useLocation(); const [albums, setAlbums] = useState<Album[]>([]); const [busy, setBusy] = useState(false); const [deletingId, setDeletingId] = useState<number | null>(null); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState("");
  const load = async () => { setLoading(true); setLoadError(""); try { const response = await fetch(`${getApiUrl()}/api/admin/gallery/albums`, { headers: headers() }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Unable to load gallery"); setAlbums(data); } catch (error: any) { setLoadError(error.message || "Unable to load gallery"); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const create = async () => { const title = window.prompt("Album name"); if (!title?.trim()) return; const description = window.prompt("Album description (optional)") || null; setBusy(true); try { const response = await fetch(`${getApiUrl()}/api/gallery/albums`, { method: "POST", headers: { ...headers(), "Content-Type": "application/json" }, body: JSON.stringify({ title: title.trim(), description, year: new Date().getFullYear(), isPublished: false }) }); const album = await response.json(); if (!response.ok) throw new Error(album.error || "Could not create album"); toast.success("Album created"); navigate(`/admin/gallery/${album.slug}`); } catch (error: any) { toast.error(error.message || "Could not create album"); } finally { setBusy(false); }
    };
    const removeAlbum = async (album: Album) => { if (!isSuperAdmin || !window.confirm(`Delete album “${album.title}” and all ${album.photoCount} photos?`)) return; setDeletingId(album.id); try { const response = await fetch(`${getApiUrl()}/api/gallery/albums/${album.id}`, { method: "DELETE", headers: headers() }); if (!response.ok) { const result = await response.json(); throw new Error(result.error || "Could not delete album"); } toast.success("Album and its photos deleted"); await load(); } catch (error: any) { toast.error(error.message || "Could not delete album"); } finally { setDeletingId(null); } };
  if (isVolunteer) return <main className="min-h-screen bg-[#080808] p-8 text-white">You do not have access to gallery management.</main>;
  return <main className="min-h-screen bg-[#080808] px-4 py-8 text-white sm:px-8"><div className="mx-auto max-w-6xl"><div className="mb-8 flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[.25em] text-amber-300/70">Administration</p><h1 className="mt-2 text-3xl font-semibold">Gallery</h1><p className="mt-2 text-sm text-white/45">Manage your community photo albums.</p></div><button onClick={() => void create()} disabled={busy} className="inline-flex items-center gap-2 rounded-xl bg-amber-300 px-4 py-3 text-sm font-semibold text-black disabled:opacity-50"><Plus className="h-4 w-4" />Create Album</button></div>{loading ? <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[1,2,3].map((item) => <div key={item} className="h-80 animate-pulse rounded-2xl border-white/10 bg-white/[.04]" />)}</div> : loadError ? <div className="rounded-2xl border-red-400/20 bg-red-400/5 p-10 text-center"><p className="text-red-200">Unable to load gallery</p><button onClick={() => void load()} className="mt-4 rounded-lg border-white/15 px-4 py-2 text-sm">Retry</button></div> : albums.length ? <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{albums.map((album) => <article key={album.id} className="overflow-hidden rounded-2xl border-white/10 bg-white/[.04]">{album.coverImageUrl ? <img src={album.coverImageUrl} alt="" className="h-40 w-full object-cover" /> : <div className="flex h-40 items-center justify-center bg-white/[.03]"><FolderOpen className="h-10 w-10 text-amber-300/40" /></div>}<div className="p-5"><h2 className="text-lg font-semibold">{album.title}</h2><p className="mt-2 text-sm text-white/45">{album.description || "Community memories"}</p><p className="mt-3 text-sm text-white/60">{album.photoCount} photos</p><p className="mt-2 text-xs text-amber-200">{album.isPublished ? "Published" : "Unpublished"}</p><div className="mt-5 flex-wrap gap-2"><button onClick={() => navigate(`/admin/gallery/${album.slug}`)} className="inline-flex items-center gap-2 rounded-lg border-amber-300/30 px-3 py-2 text-sm font-semibold text-amber-200"><FolderOpen className="h-4 w-4" />Open Album</button>{isSuperAdmin && <button onClick={() => void removeAlbum(album)} disabled={deletingId === album.id} className="inline-flex items-center gap-2 rounded-lg border-red-400/30 px-3 py-2 text-sm font-semibold text-red-300 disabled:opacity-50" title="Delete album"><Trash2 className="h-4 w-4" />{deletingId === album.id ? "Deleting…" : "Delete"}</button>}</div></div></article>)}</div> : <div className="rounded-2xl border-dashed border-white/15 p-12 text-center text-white/45"><FolderOpen className="mx-auto mb-3 h-10 w-10 text-amber-300/60" />No albums yet.</div>}</div></main>;
}
