import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Save, Trophy } from "lucide-react";
import { toast } from "sonner";
import { getApiUrl } from "@/lib/utils";
import { useAdminAuth } from "@/lib/AdminAuthContext";

type CompetitionContent = { title: string; introduction: string; rules: string[]; googleFormUrl: string | null; contactName: string; contactPhone: string; contactEmail: string };
const api = getApiUrl();
const headers = (token?: string) => token ? { Authorization: `Bearer ${token}` } : {};

export default function AdminNavratriCompetition() {
  const { user } = useAdminAuth();
  const client = useQueryClient();
  const [form, setForm] = useState({ title: "", introduction: "", rules: "", googleFormUrl: "", contactName: "", contactPhone: "", contactEmail: "" });
  const content = useQuery<CompetitionContent>({ queryKey: ["admin-navratri-competition"], enabled: !!user?.token, queryFn: async () => { const r = await fetch(`${api}/api/admin/navratri-competition`, { headers: headers(user?.token) }); if (!r.ok) throw new Error("Unable to load competition content"); return r.json(); } });

  useEffect(() => { if (content.data) setForm({ ...content.data, googleFormUrl: content.data.googleFormUrl || "", rules: content.data.rules.join("\n") }); }, [content.data]);
  const save = useMutation({ mutationFn: async () => { const r = await fetch(`${api}/api/admin/navratri-competition`, { method: "PATCH", headers: { ...headers(user?.token), "Content-Type": "application/json" }, body: JSON.stringify({ ...form, rules: form.rules.split(/\r?\n/).map((rule) => rule.trim()).filter(Boolean) }) }); const data = await r.json().catch(() => ({})); if (!r.ok) throw new Error(data.error || "Unable to save competition content"); return data; }, onSuccess: (data) => { client.setQueryData(["admin-navratri-competition"], data); client.invalidateQueries({ queryKey: ["navratri-competition-content"] }); toast.success("Navratri competition content updated."); }, onError: (error: Error) => toast.error(error.message) });
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const field = "mt-1 w-full rounded-lg border bg-background px-3 py-2.5 text-sm outline-none focus:ring-2 focus:ring-primary/40";

  return <main className="min-h-screen bg-[var(--page-bg)] pb-16 pt-24 text-foreground"><div className="mx-auto max-w-4xl px-4 sm:px-6"><header className="mb-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-primary">Admin Panel</p><h1 className="mt-1 flex items-center gap-3 font-serif text-3xl font-semibold sm:text-4xl"><Trophy className="h-8 w-8 text-primary" /> Navratri Competition Content</h1><p className="mt-2 text-sm text-muted-foreground">Manage the public announcement, rules, contact details and Google Form link. One rule per line controls the public order.</p></header>{content.isLoading ? <p className="py-16 text-center text-muted-foreground">Loading content...</p> : content.isError ? <p className="rounded-xl border-destructive/30 bg-destructive/10 p-6 text-destructive">Unable to load competition content.</p> : <form onSubmit={(event) => { event.preventDefault(); save.mutate(); }} className="space-y-6 rounded-2xl border-white/10 bg-white/[0.04] p-5 shadow-xl sm:p-8"><label className="block text-sm font-semibold">Competition Title<input className={field} value={form.title} onChange={(e) => update("title", e.target.value)} required /></label><label className="block text-sm font-semibold">Short Introduction<textarea className={field} rows={3} value={form.introduction} onChange={(e) => update("introduction", e.target.value)} required /></label><label className="block text-sm font-semibold">Rules &amp; Regulations<textarea className={field} rows={8} value={form.rules} onChange={(e) => update("rules", e.target.value)} placeholder="One rule per line" /></label><label className="block text-sm font-semibold">Google Form URL<p className="mt-1 text-xs font-normal text-muted-foreground">Only https://docs.google.com/forms/... or https://forms.gle/... URLs are accepted.</p><input className={field} type="url" value={form.googleFormUrl} onChange={(e) => update("googleFormUrl", e.target.value)} placeholder="https://forms.gle/..." /></label><div className="grid gap-4 sm:grid-cols-3"><label className="block text-sm font-semibold">Contact Name<input className={field} value={form.contactName} onChange={(e) => update("contactName", e.target.value)} required /></label><label className="block text-sm font-semibold">Contact Number<input className={field} value={form.contactPhone} onChange={(e) => update("contactPhone", e.target.value)} required /></label><label className="block text-sm font-semibold">Contact Email<input className={field} type="email" value={form.contactEmail} onChange={(e) => update("contactEmail", e.target.value)} required /></label></div><button type="submit" disabled={save.isPending} className="inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-primary px-5 text-sm font-bold text-primary-foreground shadow-lg hover:bg-primary/90 disabled:opacity-50 sm:w-auto"><Save className="h-4 w-4" />{save.isPending ? "Saving..." : "Save Competition Content"}</button></form>}</div></main>;
}
